.create-or-alter function  GetDigitalTwinIdForUANode(stationName:string,location:string,displayName:string) {
let dataHistoryTable = <tableName>; // set to the name of your property data history table
let dtId = toscalar(dataHistoryTable
| where TimeStamp between (todatetime(now() - datetime(01:00:00)) .. now())
| where Key == 'equipmentID'
| where Value has stationName
| where Value  has location
| where Value has displayName
| project Id);
print dtId
}
