@startjson AksEdgeDeploy
<style>
jsonDiagram {
    node {
        FontSize 12
        RoundCorner 10
        LineThickness 0.5
        separator {
            LineThickness 0.25
        }
    }
    arrow {
        LineThickness 0.5
        LineStyle 2;6
    }
    highlight {
        BackgroundColor black
        FontColor White
    }
}
</style>
#highlight "SchemaVersion"
{
    "SchemaVersion":"1.1",
    "Version":"1.0",
    "AksEdgeProduct" : [
                "AKS Edge Essentials - K8s (Public Preview)",
                "AKS Edge Essentials - K3s (Public Preview)"
            ],
    "AksEdgeProductUrl" : "URL",
    "Azure":{
        "ClusterName":"String",
        "SubscriptionName":"String",
        "SubscriptionId": "GUID",
        "TenantId":"GUID",
        "ResourceGroupName": "String",
        "ServicePrincipalName" : "String",
        "Location" : "String",
        "CustomLocationOID":"GUID",
        "Auth": {
            "ServicePrincipalId" : "GUID",
            "Password" : "String"
        }
    }
    ,
    "InstallOptions":{
        "InstallPath":"String",
        "VhdxPath":"String"
    }
    ,
    "VSwitch": {
        "Name": "String",
        "AdapterName": "String"
    }
    ,
    "AksEdgeConfigFile":"String",
    "AksEdgeConfig":{
        "ref" :"aksedge-config.json"
    }
}
@endjson