apiVersion: v1
kind: Namespace
metadata:
  name: seattle
spec:
  finalizers:
  - kubernetes
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ua-cloudpublisher
  namespace: seattle
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ua-cloudpublisher
  template:
    metadata:
      labels:
        app: ua-cloudpublisher
    spec:
      nodeSelector:
        "kubernetes.io/os": linux
      containers:
      - name: ua-cloudpublisher
        image: ghcr.io/barnstee/ua-cloudpublisher:main
        imagePullPolicy: Always
        env:
        - name: OPCUA_USERNAME
          value: "myUsername"
        - name: OPCUA_PASSWORD
          value: "myPassword"
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: "settings"
          mountPath: "/app/settings"
      volumes:
        - name: "settings"
          hostPath:
            path: "/mnt/c/K3s/PublisherConfig/Seattle"
---
apiVersion: v1
kind: Service
metadata:
  name: ua-cloudpublisher
  namespace: seattle
spec:
  type: LoadBalancer
  ports:
  - targetPort: 8080
    port: 8080
  selector:
    app: ua-cloudpublisher
