apiVersion: v1
kind: Namespace
metadata:
  name: munich
spec:
  finalizers:
  - kubernetes
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mes
  namespace: munich
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mes
  template:
    metadata:
      labels:
        app: mes
    spec:
      nodeSelector:
        "kubernetes.io/os": linux
      containers:
      - name: mes
        image: ghcr.io/digitaltwinconsortium/manufacturingontologies:main
        env:
        - name: StationType
          value: "MES"
        - name: ProductionLineName
          value: "munich"
        - name: STORAGE_CONNECTION_STRING
          value: "DefaultEndpointsProtocol=https;AccountName=[yourstorageaccountname];AccountKey=[key];EndpointSuffix=core.windows.net"
        - name: STORAGE_CONTAINER_NAME
          value: "munich"
---
apiVersion: v1
kind: Service
metadata:
  name: mes
  namespace: munich
spec:
  ports:
  - port: 8080
  selector:
    app: mes
