{
 "title": "Manufacturing Ontology dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "auto",
 "templating": {
  "list": [
   { "name": "Station", "query": "assembly, test, packaging" },
   { "name": "Location", "query": "munich, seattle" },
   { "name": "CycleTime", "query": "6000, 10000" }
  ]
 },
 "panels": [
  {
   "title": "Company",
   "type": "text",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 0 },
   "options": {
    "content": "<div style=\"font-style: italic; text-align: center;\" markdown=\"1\">\r\n\r\n# Contoso Factory\r\n\r\n</div>"
   },
   "targets": [
    {
     "database": "ontologies",
     "expression": {
      "from": { "property": { "name": "AdtPropertyEvents", "type": "string" }, "type": "property" },
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "let ADTInstance = \"${adtURL}\"; \nlet ADTQuery = \"SELECT T.equipmentID FROM DIGITALTWINS T WHERE IS_OF_MODEL(T , 'dtmi:digitaltwins:isa95:Area;1')\";\nevaluate azure_digital_twins_query_request(ADTInstance, ADTQuery)\n| extend factory = substring(equipmentID, 10, 15)\n| project factory",
     "querySource": "raw"
    }
   ]
  },
  {
   "title": "OEE Station",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 7, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "database": "ontologies",
     "expression": {
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "print round (CalculateOEEForStation('${Station}', '${Location}', '${CycleTime}', '${__from:date:iso}', '${__to:date:iso}') * 100, 2)",
     "querySource": "raw"
    }
   ]
  },
  {
   "title": "OEE Line",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "database": "ontologies",
     "expression": {
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "print round(CalculateOEEForLine('${Location}', '${CycleTime}', '${__from:date:iso}', '${__to:date:iso}') * 100, 2)",
     "querySource": "raw"
    }
   ]
  },
  {
   "title": "Discarded products",
   "type": "stat",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "database": "ontologies",
     "query": "opcua_metadata_lkv\r\n| where Name contains '${Station}'\r\n| where Name contains '${Location}'\r\n| join kind=inner (opcua_telemetry\r\n| where Name == \"NumberOfDiscardedProducts\"\r\n| where Timestamp > todatetime('${__from:date:iso}') and Timestamp < todatetime('${__to:date:iso}')\r\n) on DataSetWriterID\r\n| extend numProd = toint(Value)\r\n| summarize max(numProd)"
    }
   ]
  },
  {
   "title": "Manufactured products",
   "type": "stat",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "database": "ontologies",
     "expression": {
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "opcua_metadata_lkv\r\n| where Name contains '${Station}'\r\n| where Name contains '${Location}'\r\n| join kind=inner (opcua_telemetry\r\n| where Name == \"NumberOfManufacturedProducts\"\r\n| where Timestamp > todatetime('${__from:date:iso}') and Timestamp < todatetime('${__to:date:iso}')\r\n) on DataSetWriterID\r\n| extend numProd = toint(Value)\r\n| summarize max(numProd)",
     "querySource": "raw"
    }
   ]
  },
  {
   "title": "Assembly ${Location} Energy Consumption",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "database": "ontologies",
     "expression": {
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "opcua_metadata_lkv\r\n| where Name contains '${Station}'\r\n| where Name contains '${Location}'\r\n| join kind=inner (opcua_telemetry\r\n    | where Name == \"EnergyConsumption\"\r\n    | where Timestamp > todatetime('${__from:date:iso}') and Timestamp < todatetime('${__to:date:iso}')\r\n) on DataSetWriterID\r\n| extend NodeValue = todouble(Value)\r\n| project Timestamp1, NodeValue",
     "querySource": "raw"
    }
   ]
  },
  {
   "title": "Pressure",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "pressurembar" } },
   "targets": [
    {
     "database": "ontologies",
     "expression": {
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "opcua_metadata_lkv\r\n| where Name contains '${Station}'\r\n| where Name contains '${Location}'\r\n| join kind=inner (opcua_telemetry\r\n    | where Name == \"Pressure\"\r\n    | where Timestamp > todatetime('${__from:date:iso}') and Timestamp < todatetime('${__to:date:iso}')\r\n) on DataSetWriterID\r\n| extend NodeValue = toint(Value)\r\n| project Timestamp1, NodeValue",
     "querySource": "raw"
    }
   ]
  }
 ]
}